dataset: "LibriTTS"

path:
  corpus_path: "/home/winddori/nvme0partition/data/tts/libri/LibriTTS/test-clean"             ### [train-other-500, train-clean-360, train-clean-100, test-clen]
  lexicon_path: "lexicon/new_librispeech-lexicon.txt"
  raw_path: "/home/winddori/nvme0partition/data/tts/libri/LibriTTS/raw_data_test_clean"
  preprocessed_path: "/home/winddori/nvme0partition/data/tts/libri/LibriTTS/preprocessed_data_test_clean"

preprocessing:
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 
